// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/intunderflow/metal-infra-config/services/peerdiscovery (interfaces: PeerDiscovery)
//
// Generated by this command:
//
//	mockgen -destination services/peerdiscovery/mock/peerdiscovery.go github.com/intunderflow/metal-infra-config/services/peerdiscovery PeerDiscovery
//

// Package mock_peerdiscovery is a generated GoMock package.
package mock_peerdiscovery

import (
	reflect "reflect"

	entities "github.com/intunderflow/metal-infra-config/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockPeerDiscovery is a mock of PeerDiscovery interface.
type MockPeerDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockPeerDiscoveryMockRecorder
}

// MockPeerDiscoveryMockRecorder is the mock recorder for MockPeerDiscovery.
type MockPeerDiscoveryMockRecorder struct {
	mock *MockPeerDiscovery
}

// NewMockPeerDiscovery creates a new mock instance.
func NewMockPeerDiscovery(ctrl *gomock.Controller) *MockPeerDiscovery {
	mock := &MockPeerDiscovery{ctrl: ctrl}
	mock.recorder = &MockPeerDiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeerDiscovery) EXPECT() *MockPeerDiscoveryMockRecorder {
	return m.recorder
}

// GetPeers mocks base method.
func (m *MockPeerDiscovery) GetPeers() ([]entities.Peer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeers")
	ret0, _ := ret[0].([]entities.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeers indicates an expected call of GetPeers.
func (mr *MockPeerDiscoveryMockRecorder) GetPeers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockPeerDiscovery)(nil).GetPeers))
}
