// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/intunderflow/metal-infra-config/proto (interfaces: MetalInfraConfigClient,MetalInfraConfig_SyncClient)
//
// Generated by this command:
//
//	mockgen -destination proto/mock/mock.go github.com/intunderflow/metal-infra-config/proto MetalInfraConfigClient,MetalInfraConfig_SyncClient
//

// Package mock_proto is a generated GoMock package.
package mock_proto

import (
	context "context"
	reflect "reflect"

	proto "github.com/intunderflow/metal-infra-config/proto"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMetalInfraConfigClient is a mock of MetalInfraConfigClient interface.
type MockMetalInfraConfigClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetalInfraConfigClientMockRecorder
}

// MockMetalInfraConfigClientMockRecorder is the mock recorder for MockMetalInfraConfigClient.
type MockMetalInfraConfigClientMockRecorder struct {
	mock *MockMetalInfraConfigClient
}

// NewMockMetalInfraConfigClient creates a new mock instance.
func NewMockMetalInfraConfigClient(ctrl *gomock.Controller) *MockMetalInfraConfigClient {
	mock := &MockMetalInfraConfigClient{ctrl: ctrl}
	mock.recorder = &MockMetalInfraConfigClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetalInfraConfigClient) EXPECT() *MockMetalInfraConfigClientMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockMetalInfraConfigClient) Set(arg0 context.Context, arg1 *proto.SetRequest, arg2 ...grpc.CallOption) (*proto.SetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(*proto.SetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockMetalInfraConfigClientMockRecorder) Set(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMetalInfraConfigClient)(nil).Set), varargs...)
}

// Sync mocks base method.
func (m *MockMetalInfraConfigClient) Sync(arg0 context.Context, arg1 ...grpc.CallOption) (proto.MetalInfraConfig_SyncClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync", varargs...)
	ret0, _ := ret[0].(proto.MetalInfraConfig_SyncClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockMetalInfraConfigClientMockRecorder) Sync(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockMetalInfraConfigClient)(nil).Sync), varargs...)
}

// MockMetalInfraConfig_SyncClient is a mock of MetalInfraConfig_SyncClient interface.
type MockMetalInfraConfig_SyncClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetalInfraConfig_SyncClientMockRecorder
}

// MockMetalInfraConfig_SyncClientMockRecorder is the mock recorder for MockMetalInfraConfig_SyncClient.
type MockMetalInfraConfig_SyncClientMockRecorder struct {
	mock *MockMetalInfraConfig_SyncClient
}

// NewMockMetalInfraConfig_SyncClient creates a new mock instance.
func NewMockMetalInfraConfig_SyncClient(ctrl *gomock.Controller) *MockMetalInfraConfig_SyncClient {
	mock := &MockMetalInfraConfig_SyncClient{ctrl: ctrl}
	mock.recorder = &MockMetalInfraConfig_SyncClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetalInfraConfig_SyncClient) EXPECT() *MockMetalInfraConfig_SyncClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMetalInfraConfig_SyncClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMetalInfraConfig_SyncClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMetalInfraConfig_SyncClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMetalInfraConfig_SyncClient) Recv() (*proto.SyncRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.SyncRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMetalInfraConfig_SyncClient) RecvMsg(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) RecvMsg(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMetalInfraConfig_SyncClient) Send(arg0 *proto.SyncRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m *MockMetalInfraConfig_SyncClient) SendMsg(arg0 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) SendMsg(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMetalInfraConfig_SyncClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMetalInfraConfig_SyncClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMetalInfraConfig_SyncClient)(nil).Trailer))
}
